apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: sse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports: 
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: sse
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: my-nginx

---
# 쿠버네티스에서 https 인증서 적용 절차
# 1.cert-manager생성
  # 1-1.cert-manager 생성을 위한 cert-manager namespace생성 : kubectl create namespace cert-manager
  # 1-2.helm 패키지 매니저 설치 : 구글 검색후 다운로드 후 로컬에 설치
  # 1-3.helm repository 추가 : helm repo add jetstack https://charts.jetstack.io
  # 1-4.helm repository update : helm repo update
  # 1-5.helmn을 통해 cert-manager 설치 : helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.5.0 --set installCRDs=true

# 2.ClusterIssuer 생성
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: sse
spec:
  acme:
  # 인증서 서버 주소. 해당 서버의 리소스를 통해 인증서 발행
    server: https://acme-v02.api.letsencrypt.org/directory
    email: helloworld@naver.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
# 3.Certificate 생성
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seho-com-tls
  namespace: sse
spec: 
  secretName: seho-com-tls
  duration: 2160h #90일
  renewBefore: 360h #15일전에 갱신
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: server.ssebao.shop
  dnsNames:
  - server.ssebao.shop

  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-nginx-ingress
  namespace: sse
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$1 => prefix 제거해 주는 역할
    nginx.ingress.kubernetes.io/rewrite-target: /$1 
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - "server.ssebao.shop"
    secretName: seho-com-tls
  rules:
  - host: server.ssebao.shop
    http:
      paths:
      - path: /product-service/(.*) 
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      - path: /order-service/(.*) 
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80