apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: sse
spec:
  # node를 통해 직접 접근가능한 타입
  type: NodePort
  ports:
  - port: 80 # service port 의미 - http의 80
    targetPort: 80 # service가 라우팅해줄 대상의(pod) port - nginx의 80
    nodePort: 30601
  # pod의 labels.app과 service의 selector.app이 일치해야함에 유의
  selector:
    app: my-nginx