apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  namespace: sse
  labels:
    app: my-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  namespace: sse
  labels:
    app: my-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: sse
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30601
  selector:
  # my-nginx 라벨이 붙은 pod들한테 전달한다는 의미
    app: my-nginx
